
(function(c){function k(b){return b.replace(/^\//,"").replace(/(index|default).[a-zA-Z]{3,4}$/,"").replace(/\/$/,"")}var l=k(location.pathname),m=function(b){var d=[],a=false,e=b.dir&&b.dir=="left"?"scrollLeft":"scrollTop";this.each(function(){if(!(this==document||this==window)){var f=c(this);if(f[e]()>0)d.push(this);else{f[e](1);a=f[e]()>0;f[e](0);a&&d.push(this)}}});if(b.el==="first"&&d.length)d=[d.shift()];return d};c.fn.extend({scrollable:function(b){return this.pushStack(m.call(this,{dir:b}))},firstScrollable:function(b){return this.pushStack(m.call(this,{el:"first",dir:b}))},smoothScroll:function(b){b=b||{};var d=c.extend({},c.fn.smoothScroll.defaults,b);this.die("click.smoothscroll").live("click.smoothscroll",function(a){var e=c(this),f=location.hostname===this.hostname||!this.hostname,g=d.scrollTarget||(k(this.pathname)||l)===l,i=this.hash,h=true;if(!d.scrollTarget&&(!f||!g||!i))h=false;else{f=d.exclude;g=0;for(var j=f.length;h&&g<j;)if(e.is(f[g++]))h=false;f=d.excludeWithin;g=0;for(j=f.length;h&&g<j;)if(e.closest(f[g++]).length)h=false}if(h){d.scrollTarget=b.scrollTarget||i;d.link=this;a.preventDefault();c.smoothScroll(d)}});return this}});c.smoothScroll=function(b,d){var a,e,f,g=0;e="offset";var i="scrollTop",h={};if(typeof b==="number"){a=c.fn.smoothScroll.defaults;f=b}else{a=c.extend({},c.fn.smoothScroll.defaults,b||{});if(a.scrollElement){e="position";a.scrollElement.css("position")=="static"&&a.scrollElement.css("position","relative")}f=d||c(a.scrollTarget)[e]()&&c(a.scrollTarget)[e]()[a.direction]||0}a=c.extend({link:null},a);i=a.direction=="left"?"scrollLeft":i;if(a.scrollElement){e=a.scrollElement;g=e[i]()}else e=c("html, body").firstScrollable();h[i]=f+g+a.offset;e.animate(h,{duration:a.speed,easing:a.easing,complete:function(){a.afterScroll&&c.isFunction(a.afterScroll)&&a.afterScroll.call(a.link,a)}})};c.smoothScroll.version="1.4";c.fn.smoothScroll.defaults={exclude:[],excludeWithin:[],offset:0,direction:"top",scrollElement:null,scrollTarget:null,afterScroll:null,easing:"swing",speed:400}})(jQuery);jQuery.cookie=function(a,b,c){if(arguments.length>1&&String(b)!=="[object Object]"){c=jQuery.extend({},c);if(b===null||b===undefined){c.expires=-1}if(typeof c.expires==="number"){var d=c.expires,e=c.expires=new Date;e.setDate(e.getDate()+d)}b=String(b);return document.cookie=[encodeURIComponent(a),"=",c.raw?b:encodeURIComponent(b),c.expires?"; expires="+c.expires.toUTCString():"",c.path?"; path="+c.path:"",c.domain?"; domain="+c.domain:"",c.secure?"; secure":""].join("")}c=b||{};var f,g=c.raw?function(a){return a}:decodeURIComponent;return(f=(new RegExp("(?:^|; )"+encodeURIComponent(a)+"=([^;]*)")).exec(document.cookie))?g(f[1]):null}
jQuery(document).ready(function($){if(typeof tocplus!='undefined'){$.fn.shrinkTOCWidth=function(){$(this).css({width:'auto',display:'table'});if($.browser.msie&&parseInt($.browser.version)==7)
$(this).css('width','');}
/*if(tocplus.smooth_scroll==1){var target=hostname=pathname=qs=hash=null;$('body a').click(function(event){if(minVersion('1.6')){hostname=$(this).prop('hostname');pathname=$(this).prop('pathname');qs=$(this).prop('search');hash=$(this).prop('hash');}
else{hostname=$(this).attr('hostname');pathname=$(this).attr('pathname');qs=$(this).attr('search');hash=$(this).attr('hash');}
if(pathname.length>0){if(pathname.charAt(0)!='/'){pathname='/'+pathname;}}
if((window.location.hostname==hostname)&&(window.location.pathname==pathname)&&(window.location.search==qs)&&(hash!=='')){var hash_selector=hash.replace(/([ !"$%&'()*+,.\/:;<=>?@[\]^`{|}~])/g,'\\$1');if($(hash_selector).length>0)
target=hash;else{anchor=hash;anchor=anchor.replace('#','');target='a[name="'+anchor+'"]';if($(target).length==0)
target='';}
var offset=-30;if(typeof tocplus.smooth_scroll_offset!='undefined')
offset=-1*tocplus.smooth_scroll_offset;if(target){$.smoothScroll({scrollTarget:target,offset:offset});}}});}*/
if(typeof tocplus.visibility_show!='undefined'){var invert=(typeof tocplus.visibility_hide_by_default!='undefined')?true:false;if($.cookie)
var visibility_text=($.cookie('tocplus_hidetoc'))?tocplus.visibility_show:tocplus.visibility_hide;else
var visibility_text=tocplus.visibility_hide;if(invert)
visibility_text=(visibility_text==tocplus.visibility_hide)?tocplus.visibility_show:tocplus.visibility_hide;$('#toc_container p.toc_title').append(' <span class="toc_toggle">[<a href="#">'+visibility_text+'</a>]</span>');if(visibility_text==tocplus.visibility_show){$('ul.toc_list').hide();$('#toc_container').shrinkTOCWidth();}
$('span.toc_toggle a').click(function(event){event.preventDefault();switch($(this).html()){case $('<div/>').html(tocplus.visibility_hide).text():$(this).html(tocplus.visibility_show);if($.cookie){if(invert)
$.cookie('tocplus_hidetoc',null,{path:'/'});else
$.cookie('tocplus_hidetoc','1',{expires:30,path:'/'});}
$('ul.toc_list').hide('fast');$('#toc_container').shrinkTOCWidth();break;case $('<div/>').html(tocplus.visibility_show).text():default:$(this).html(tocplus.visibility_hide);if($.cookie){if(invert)
$.cookie('tocplus_hidetoc','1',{expires:30,path:'/'});else
$.cookie('tocplus_hidetoc',null,{path:'/'});}
$('#toc_container').css('width',tocplus.width);$('ul.toc_list').show('fast');}});}}
function minVersion(version){var $vrs=window.jQuery.fn.jquery.split('.'),min=version.split('.');for(var i=0,len=$vrs.length;i<len;i++){if(min[i]&&$vrs[i]<min[i]){return false;}}
return true;}});